language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies

# command to run tests
script: nosetests

# Here we install the ubuntu dependencies with apt-get.
before_install:
  - sudo apt-get update
  - sudo apt-get install python-numpy
